version: '3.4'

services:
  yipin-toolsite:
    container_name: yipin-toolsite-c
    image: registry.cn-qingdao.aliyuncs.com/leon-pu/yipin-toolsite:latest
    build:
      context: .
      dockerfile: ToolSite/Dockerfile
    volumes:
      - "/var/yipin/toolsite/wwwroot/tmp:/app/wwwroot/tmp"
      - "/var/yipin/toolsite/cache:/app/wwwroot/cache"
      - "/var/yipin/toolsite/logs:/app/logs"
    ports:
      - "9871:80"
    restart: always