version: '3.4'

services:
  my-test-toolsite:
    container_name: my-test-toolsite-c
    image: my-test-toolsite:latest
    build:
      context: .
      dockerfile: ToolSite/Dockerfile
    volumes:
      - "/var/leon-test/my-test-toolsite/wwwroot/tmp:/app/wwwroot/tmp"
    ports:
      - "9871:80"
    restart: always